FROM 32bit/ubuntu:14.04
RUN apt-get update && \
     apt-get install --no-install-recommends -y \
     arptables \
     bridge-utils \
     ca-certificates \
     curl \
     iptables \
     libaio1 \
     python-eventlet \
     python-minimal
RUN curl -s https://bootstrap.pypa.io/get-pip.py > get-pip.py && python get-pip.py && rm get-pip.py
RUN pip install cattle docker-py 
RUN apt-get update && apt-get install -y --no-install-recommends libssl-dev python-dev libffi-dev gcc &&\
    pip install --upgrade requests[security]==2.7.0 &&\
    apt-get remove -y --purge python-dev libffi-dev libssl-dev gcc && apt-get autoremove -y
# JQ
RUN apt-get install -y --no-install-recommends jq

# Docker
RUN apt-get install -y --no-install-recommends apt-transport-https
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
RUN echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
RUN apt-get update
RUN apt-get install -y --no-install-recommends docker.io

RUN curl -s -L https://github.com/rancherio/thin-provisioning-tools/releases/download/rancher-v0.1/pdata_tools > /usr/bin/pdata_tools; chmod +x /usr/bin/pdata_tools
RUN apt-get update && apt-get install -y --no-install-recommends conntrack
RUN mkdir -p /var/lib/cattle /var/lib/rancher
COPY register.py resolve_url.py agent.sh run.sh /
ENTRYPOINT ["/run.sh"]
LABEL "io.rancher.container.system"="rancher-agent"
ENV RANCHER_AGENT_IMAGE rancher/agent:v0.8.2
