## ARMv7 Ubuntu
FROM armv7/armhf-ubuntu:14.04.2
MAINTAINER Emil 'Skeen' Madsen <sovende@gmail.com>

RUN apt-get update
RUN apt-get install -y git build-essential libncurses5-dev libslang2-dev gettext zlib1g-dev libselinux1-dev debhelper lsb-release pkg-config po-debconf autoconf automake autopoint libtool

RUN git clone git://git.kernel.org/pub/scm/utils/util-linux/util-linux.git util-linux
WORKDIR util-linux/

RUN ./autogen.sh
RUN ./configure --without-python --disable-all-programs --enable-nsenter
RUN make

ENTRYPOINT ["/bin/bash"]
